server
{
  listen 80;
  underscores_in_headers on;

  location /ui
  {
    root /var/web;
    index index.html index.htm;
    try_files $uri $uri/ /ui/index.html;
  }
  location /m/ {
    try_files $uri $uri/ /m/cases/__placeholder__/index.html /m/index.html;
  }
}
